-- Initialize Database
CREATE DATABASE IF NOT EXISTS intern_tracker;
USE intern_tracker;

-- Companies Table
CREATE TABLE IF NOT EXISTS companies (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL
);

-- Users Table
CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    role ENUM('admin', 'intern') DEFAULT 'intern',
    company_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL
);

-- Attendance Records Table
CREATE TABLE IF NOT EXISTS attendance_records (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    date DATE NOT NULL,
    status ENUM('present', 'absent', 'late') NOT NULL,
    morning_start TIME,
    morning_end TIME,
    afternoon_start TIME,
    afternoon_end TIME,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_user_date (user_id, date),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Seed Data (Initial Companies)
INSERT INTO companies (name) VALUES 
('Corapi SRL'), 
('Giarvit'), 
('IFM'), 
('Sinapsys')
ON DUPLICATE KEY UPDATE name=name;

-- Seed Data (Admin User - password: 'admin123' hashed with bcrypt)
-- Note: You should replace this hash with a real one generated by your app if needed. 
-- For now, we will insert it manually or let the app handle registration.
-- This is a placeholder for development convenience.
-- $2a$10$YourHashedPasswordHere usually requires the app to generate it.
